version: "3.8"
services:
  server:
    image: wishsuite
    build:
      dockerfile: Dockerfile.dev
      context: .
    command: yarn run start
    working_dir: /app
    volumes:
      - .:/app/
      - notused:/app/node_modules
    environment:
      NODE_ENV: development # Has to be passed into the Docker container in order to allow dev dependencies
      DATABASE_URL: "postgresql://user:password@db_wishsuite:6543/wishsuite?connect_timeout=300"
      REDIS_HOST: redis-cache
      REDIS_PORT: 6380
      SALT_ROUNDS: 10
      SESSION_SECRET: sessionSecret
    ports:
      - 4000:4000
      - 9090:9090
    depends_on:
      - db_wishsuite
      - redis-cache
    links:
      - "db_wishsuite"
      - "redis-cache"
    container_name: wishsuite
  db_wishsuite:
    image: postgres
    command: -p 6543
    ports:
      - 6543:6543
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: wishsuite
  
  redis-cache:
    image: redis
    container_name: redis-cache
    command: redis-server --port 6380
    ports:
      - 6380:6380

volumes:
    notused:

networks:
  default:
    external: true
    name: wishsuite_default